---

  - name: yum install GPU driver dependencies
    yum:
      name: [
             "dkms",
             "glibc-devel",
             "glibc-headers",
             "kernel-devel",
             "kernel-headers",
            ]
      state: latest

  - name: get CUDA toolkit
    get_url:
      url: "{{ nvidia_cuda_toolkit_runfile_url }}"
      dest: /root/
      mode: '0755'

  - name: blacklist nouveau in modprobe
    copy: src=blacklist_modprobe dest=/etc/modprobe.d/blacklist.conf

  - name: regenerate the initramfs
    shell: dracut --force

  - name: reboot
    reboot:

  - name: re-gather facts
    setup:

  - name: get kernel version
    shell: rpm -q --qf '%{version}-%{release}.%{arch}\n' kernel | tail -1
    register: kernel_ver

  - name: Run CUDA toolkit installation
    shell: "/root/{{ cuda_toolkit_installer }} {{ cuda_toolkit_args }}"

  - name: initialize GPU device
    command: nvidia-smi
