---

   - name: install OOD repo and CentOS SCL
     yum:
       name: 
        - "centos-release-scl"
        - "https://yum.osc.edu/ondemand/1.8/ondemand-release-web-1.8-1.noarch.rpm"
       state: latest

   - name: install OOD packages
     yum:
       name: 
        - "ondemand"
        - "ondemand-selinux"
        - "mod_authnz_pam"
        - "python-websockify"
        - "selinux-policy-devel"
       state: latest

   - name: Add TurboVNC repo
     get_url:
       url: https://turbovnc.org/pmwiki/uploads/Downloads/TurboVNC.repo
       dest: /etc/yum.repos.d/
       mode: '0644'
       owner: root
       group: root

   - name: Install web app dependencies
     yum:
       name:
        - "python-websockify"
        - "turbovnc"
        - "netcat"

#This should be 'off' when on a host that is mounting homedirs over NFS
   - name: selinux ondemand_manage_user_home_dir yes
     seboolean: 
       name: ondemand_manage_user_home_dir
       state: on
       persistent: yes
     when: headnode_local_homedirs == true

   - name: selinux ondemand_use_slurm yes
     seboolean: 
       name: ondemand_use_slurm
       state: on
       persistent: yes

   - name: selinux ondemand_use_torque yes
     seboolean: 
       name: ondemand_use_torque
       state: on
       persistent: yes

   - name: create tmpdir for semodule build
     file:
       state: directory
       path: /tmp/ood_sebuild
 
   - name: copy ood.te to tmp builddir
     copy:
       dest: /tmp/ood_sebuild
       src: ood.te

# This make command will compile a local.te file in the current
# directory. If you did not specify a "pp" file, the make file
# will compile all "te" files in the current directory.  After
# you compile your te file into a "pp" file, you need to install
# it using the semodule command.

   - name: compile the policy package
     command: make -f /usr/share/selinux/devel/Makefile ood.pp
     args:
       chdir: /tmp/ood_sebuild

   - name: install the ood semodule
     command: semodule -i ood.pp
     args:
       chdir: /tmp/ood_sebuild

   - name: clean up after semodule build
     file:
       path: /tmp/ood_sebuild
       state: absent

#   - name: allow http for OOD
#     firewalld:
#       zone: public
#       permanent: yes
#       service: http
#       state: enabled
#
#   - name: allow https for OOD
#     firewalld:
#       zone: public
#       permanent: yes
#       service: https
#       state: enabled
#   - fail:

   - name: start and enable httpd24 server
     service: 
       name: httpd24-httpd
       state: started
       enabled: yes

   - name: cluster.yml template
     file: 
       state: directory
       path: /etc/ood/config/clusters.d/

   - template: 
       src: cluster.yml.j2 
       dest: /etc/ood/config/clusters.d/{{ cluster_name }}.yml

   - name: ood_portal.yml template
     template: src=ood_portal.yml.j2 dest=/etc/ood/config/ood_portal.yml
   
   - name: configure ood pam authentication
     copy:
       src: /usr/lib64/httpd/modules/mod_authnz_pam.so
       dest: /opt/rh/httpd24/root/usr/lib64/httpd/modules/
   
   - copy:
       src: /etc/pam.d/sshd
       dest: /etc/pam.d/ood-webapp
   
   - lineinfile:
       path: /opt/rh/httpd24/root/etc/httpd/conf.modules.d/55-authnz_pam.conf
       create: yes
       line: 'LoadModule authnz_pam_module modules/mod_authnz_pam.so'
   
   - file:
       dest: /etc/shadow
       group: apache
       mode: 0640

   - name: update the apache config
     command: /opt/ood/ood-portal-generator/sbin/update_ood_portal

   - name: update the bc_desktop app form
     template:
       dest: /var/www/ood/apps/sys/bc_desktop/form.yml
       src: bc_desktop_form.j2

   - name: restart the httpd24 server
     service: 
       name: httpd24-httpd
       state: restarted
