---

   - name: install OOD repo and CentOS SCL
     yum:
       name: 
        - "centos-release-scl"
        - "https://yum.osc.edu/ondemand/1.8/ondemand-release-web-1.8-1.noarch.rpm"
       state: latest

   - name: install OOD packages
     yum:
       name: 
        - "ondemand"
        - "ondemand-selinux"
        - "mod_authnz_pam"
        - "python-websockify"
       state: latest

#This should be 'off' when on a host that is mounting homedirs over NFS
   - name: selinux ondemand_manage_user_home_dir yes
     seboolean: 
       name: ondemand_manage_user_home_dir
       state: on
       persistent: yes
     when: headnode_local_homedirs == true

   - name: selinux ondemand_use_slurm yes
     seboolean: 
       name: ondemand_use_slurm
       state: on
       persistent: yes

#   - name: allow http for OOD
#     firewalld:
#       zone: public
#       permanent: yes
#       service: http
#       state: enabled
#
#   - name: allow https for OOD
#     firewalld:
#       zone: public
#       permanent: yes
#       service: https
#       state: enabled
#   - fail:

   - name: start and enable httpd24 server
     service: 
       name: httpd24-httpd
       state: started
       enabled: yes

   - name: cluster.yml template
     file: 
       state: directory
       path: /etc/ood/config/clusters.d/

   - template: 
       src: cluster.yml.j2 
       dest: /etc/ood/config/clusters.d/{{ cluster_name }}.yml

   - name: ood_portal.yml template
     template: src=ood_portal.yml.j2 dest=/etc/ood/config/ood_portal.yml
   
   - name: configure ood pam authentication
     copy:
       src: /usr/lib64/httpd/modules/mod_authnz_pam.so
       dest: /opt/rh/httpd24/root/usr/lib64/httpd/modules/
   
   - copy:
       src: /etc/pam.d/sshd
       dest: /etc/pam.d/ood-webapp
   
   - lineinfile:
       path: /opt/rh/httpd24/root/etc/httpd/conf.modules.d/55-authnz_pam.conf
       create: yes
       line: 'LoadModule authnz_pam_module modules/mod_authnz_pam.so'
   
   - file:
       dest: /etc/shadow
       group: apache
       mode: 0640

   - name: update the apache config
     command: /opt/ood/ood-portal-generator/sbin/update_ood_portal
