---

  - name: install yum-utils
    yum: 
      name: yum-utils
      state: present

  - name: disable CentOS repo
    yum_repository:
      name: CentOS\*
      enabled: no
      state: present

  - name: enable headnode OpenHPC Repo
    template: 
      src: headnode_ohpc_repo.j2
      dest: /etc/yum/repos.d/local-OpenHPC.repo

  - name: enable headnode EPEL Repo
    template: 
      src: headnode_epel_repo.j2
      dest: /etc/yum/repos.d/local-EPEL.repo

  - name: set excludedocs for rpm
    shell: echo -e "%_excludedocs 1" >> /root/.rpmmacros

  - name: yum install client packages
    yum:
      name: [
             "ohpc-base-compute",
             "ohpc-slurm-client",
             "chronyd",
             "kernel",
             "lmod-ohpc",
            ]
      state: latest

   - name: add headnode to compute chrony.conf
     lineinfile: line="server {{ headnode_private_ip }}" dest=/etc/chrony.conf state=present

   - name: restart and enable chronyd
     service:
       name: chronyd
       enabled: yes
       state: restarted

