---
  
  - name: get list of non-system users in passwd
    shell: getent passwd | awk -F':' '$3 >= 1000 {print $0}'
    register: user_list_passwd

  - name: get list of non-system groups
    shell: getent group | awk -F':' '$3 >= 1000 {print $0}'
    register: user_list_groups

  - debug:
      var: "{{ user_list_passwd }}"

  - debug:
      var: "{{ user_list_groups }}"

  - fail:

  - name: get list of non-system users in shadow
    shell: getent shadow | grep $(cut -f 1 -d':' {{ item }})
    register: user_list_shadow
    loop: "{{ user_list_passwd }}"
